project:
  type: book

book:
  title: "Simulations to test correction for censored predictors"
  author: "Zane Billings"
  date: last-modified
  date-format: iso
  chapters:
    - index.qmd
    - data-simulation.qmd
    - part: "Methods"
      chapters: 
        - method-imputation.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

bibliography: censored-predictor-methods.bib
csl: aje.csl

